services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true
    public: false
    bind:

  # Services
  SimpleSAML\Module\conformance\:
    resource: '../../src/*'
