services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true
    public: false
    bind:

  # Services
  SimpleSAML\Module\conformance\:
    resource: '../../src/*'
    exclude: '../../src/{Controllers}'

  # Controllers
  SimpleSAML\Module\conformance\Controllers\:
    resource: '../../src/Controllers/*'
    tags: ['controller.service_arguments']

  # SimpleSAMLphp Services
  SimpleSAML\Metadata\MetaDataStorageHandlerPdo:
    arguments:
      - { }
  SimpleSAML\Utils\XML: ~