
conformance-overview:
  path: /overview
  controller: SimpleSAML\Module\conformance\Controllers\Overview::index

conformance-overview-run-migrations:
  path: /overview/run-migrations
  controller: SimpleSAML\Module\conformance\Controllers\Overview::runMigrations
  methods:
    - POST
    - GET

conformance-test-setup:
  path: /test/setup
  controller: SimpleSAML\Module\conformance\Controllers\TestSetup::setup

conformance-metadata-add:
  path: /metadata/add
  controller: SimpleSAML\Module\conformance\Controllers\Metadata::add
  methods:
    - GET

conformance-metadata-persist:
  path: /metadata/persist
  controller: SimpleSAML\Module\conformance\Controllers\Metadata::persist
  methods:
    - POST

conformance-nuclei-test-setup:
  path: /nuclei/test/setup
  controller: SimpleSAML\Module\conformance\Controllers\NucleiTest::setup
  methods:
    - GET

conformance-nuclei-test-fetch-acss:
  path: /nuclei/test/fetch-acss
  controller: SimpleSAML\Module\conformance\Controllers\NucleiTest::fetchAcss
  methods:
    - GET

conformance-test-run:
  path: /nuclei/test/run
  controller: SimpleSAML\Module\conformance\Controllers\NucleiTest::run
  methods:
    - POST
    - GET

conformance-nuclei-results-index:
  path: /nuclei/results
  controller: SimpleSAML\Module\conformance\Controllers\NucleiResults::index
  methods:
    - GET

conformance-nuclei-results-show:
  path: /nuclei/results/show/{id}
  controller: SimpleSAML\Module\conformance\Controllers\NucleiResults::show
  methods:
    - GET
  requirements:
    id: '\d+'

conformance-nuclei-results-get:
  path: /nuclei/results/get
  controller: SimpleSAML\Module\conformance\Controllers\NucleiResults::get
  methods:
    - GET

conformance-nuclei-results-download:
  path: /nuclei/results/download
  controller: SimpleSAML\Module\conformance\Controllers\NucleiResults::download
  methods:
    - GET

conformance-sp-consents-index:
  path: /sp-consents
  controller: SimpleSAML\Module\conformance\Controllers\SpConsent::index
  methods:
    - GET

conformance-sp-consents-verify-challenge:
  path: /sp-consents/verify-challenge
  controller: SimpleSAML\Module\conformance\Controllers\SpConsent::verifyChallenge
  methods:
    - GET